# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/video_service/video_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.video_service import video_model_pb2 as proto_dot_video__service_dot_video__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'proto/video_service/video_service.proto\x12\rvideo_service\x1a%proto/video_service/video_model.proto2a\n\x0cVideoService\x12Q\n\x0cProcessVideo\x12\x19.video_service.VideoFrame\x1a\".video_service.ProcessedVideoFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.video_service.video_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VIDEOSERVICE']._serialized_start=97
  _globals['_VIDEOSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
