# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.video_service import video_model_pb2 as proto_dot_video__service_dot_video__model__pb2


class VideoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVideo = channel.stream_stream(
                '/video_service.VideoService/ProcessVideo',
                request_serializer=proto_dot_video__service_dot_video__model__pb2.VideoFrame.SerializeToString,
                response_deserializer=proto_dot_video__service_dot_video__model__pb2.ProcessedVideoFrame.FromString,
                )


class VideoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=proto_dot_video__service_dot_video__model__pb2.VideoFrame.FromString,
                    response_serializer=proto_dot_video__service_dot_video__model__pb2.ProcessedVideoFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_service.VideoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/video_service.VideoService/ProcessVideo',
            proto_dot_video__service_dot_video__model__pb2.VideoFrame.SerializeToString,
            proto_dot_video__service_dot_video__model__pb2.ProcessedVideoFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
